# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-25 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courts',
            old_name='court_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='city',
        ),
    ]
