# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-25 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0002_auto_20180425_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='city',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
