# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-26 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0003_courts_city'),
        ('hoopfinder', '0002_auto_20180425_1514'),
    ]

    operations = [
    ]
