# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-26 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0004_merge_20180426_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court_review',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='user_review',
            name='reviewed_by',
        ),
        migrations.AlterField(
            model_name='courts',
            name='address',
            field=models.CharField(max_length=75),
        ),
        migrations.DeleteModel(
            name='Court_review',
        ),
        migrations.DeleteModel(
            name='User_review',
        ),
    ]
