# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-26 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0005_auto_20180426_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court_review_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_courts', to='hoopfinder.User')),
                ('court_reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_reviews', to='hoopfinder.Courts')),
            ],
        ),
    ]
