# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-26 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0006_court_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='checked_in_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checked_into', to='hoopfinder.User'),
            preserve_default=False,
        ),
    ]
