# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-26 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0007_courts_checked_in_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='court_review',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
