# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-27 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0009_userreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='uploaded_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='court_uploaded', to='hoopfinder.User'),
            preserve_default=False,
        ),
    ]
