# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-27 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0011_auto_20180427_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courts',
            name='checked_in_user',
        ),
    ]
