# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-09 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0012_remove_courts_checked_in_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_icon', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('location', models.IntegerField()),
            ],
        ),
    ]
