# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-10 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0014_auto_20180509_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='height',
            new_name='feet',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='inches',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
