# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-10 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0015_auto_20180509_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='feet',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='inches',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
