# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-10 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0017_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friended_by',
            field=models.ManyToManyField(related_name='users_friends', to='hoopfinder.User'),
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
