# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-10 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0020_auto_20180509_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ManyToManyField(to='hoopfinder.User'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friended_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='users_friends', to='hoopfinder.User'),
        ),
    ]
