# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-10 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0023_auto_20180510_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_friends', to='hoopfinder.User'),
        ),
    ]
