# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-10 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0024_auto_20180510_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friended_by',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='friend',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='hoopfinder.User'),
        ),
        migrations.AddField(
            model_name='friend',
            name='users',
            field=models.ManyToManyField(to='hoopfinder.User'),
        ),
    ]
