# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0026_auto_20180511_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='court',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userreviews',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='userreviews',
            name='reviewed_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='feet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='inches',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_icon',
        ),
        migrations.AddField(
            model_name='courts',
            name='checked_in_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checked_into', to='hoopfinder.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='UserReviews',
        ),
    ]
