# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0027_auto_20190218_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default=b' ', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=b' ', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='feet',
            field=models.CharField(default=b' ', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='inches',
            field=models.CharField(default=b' ', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default=b' ', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default=b' ', max_length=255),
        ),
    ]
