# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0029_userreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
