# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0032_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='hoopfinder.User'),
            preserve_default=False,
        ),
    ]
