# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0033_followers_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={},
        ),
    ]
