# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0034_auto_20190404_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='user',
        ),
    ]
