# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0035_remove_followers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='user_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
