# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoopfinder', '0036_followers_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followers',
        ),
    ]
